application: eventious-1
version: dev-001
runtime: php55
api_version: 1
instance_class: F1
threadsafe: true
#automatic_scaling:
 # min_idle_instances: 5
 # max_idle_instances: 25
 # min_pending_latency: 100ms
 # max_pending_latency: 500ms

handlers:

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.html)$
  script: /index.html

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

# Serve php scripts.
- url: /
  script: /index.html


- url: /index.html
  script: /index.html

- url: /about
  script: /?c=about

# Serve javascript scripts.
- url: /(.+\.js)$
  script: \1

# Serve stylesheets
- url: /inc/css
  static_dir: inc/css

# Serve images
- url: /inc/ass/img
  static_dir: inc/ass/img



